security:
    encoders:
        App\Entity\Trainer:
            algorithm: bcrypt
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        users_in_memory: { memory: null }
        in_database:
            entity:
                class: App\Entity\Trainer
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            access_denied_url: /redirect

            anonymous: true

            provider: in_database

            form_login:
                login_path: security_login
                check_path: security_login

            logout:
                path: security_logout
                target: /connexion
            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true
    
    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/admin, roles: 'ROLE_ADMIN' }
        - { path: ^/all_trainers, roles: 'ROLE_ADMIN' }
        - { path: ^/trainer, roles: 'IS_AUTHENTICATED_FULLY' }
        - { path: ^/balls, roles: 'IS_AUTHENTICATED_FULLY'}
        - { path: ^/pokemons, roles: 'IS_AUTHENTICATED_FULLY' }
        - { path: ^/potions, roles: 'IS_AUTHENTICATED_FULLY' }
        - { path: ^/balls, roles: 'IS_AUTHENTICATED_FULLY' }
        - { path: ^/attacks, roles: 'IS_AUTHENTICATED_FULLY' }
        - { path: ^/team, roles: 'IS_AUTHENTICATED_FULLY' }
        - { path: ^/fire, roles: 'IS_AUTHENTICATED_FULLY' }
        - { path: ^/water, roles: 'IS_AUTHENTICATED_FULLY' }
        - { path: ^/grass, roles: 'IS_AUTHENTICATED_FULLY' }
        - { path: ^/bug, roles: 'IS_AUTHENTICATED_FULLY' }
        - { path: ^/dragon, roles: 'IS_AUTHENTICATED_FULLY' }
        - { path: ^/elektrik, roles: 'IS_AUTHENTICATED_FULLY' }
        - { path: ^/fighting, roles: 'IS_AUTHENTICATED_FULLY' }
        - { path: ^/fly, roles: 'IS_AUTHENTICATED_FULLY' }
        - { path: ^/ghost, roles: 'IS_AUTHENTICATED_FULLY' }
        - { path: ^/ground, roles: 'IS_AUTHENTICATED_FULLY' }
        - { path: ^/ice, roles: 'IS_AUTHENTICATED_FULLY' }
        - { path: ^/normal, roles: 'IS_AUTHENTICATED_FULLY' }
        - { path: ^/poison, roles: 'IS_AUTHENTICATED_FULLY' }
        - { path: ^/psy, roles: 'IS_AUTHENTICATED_FULLY' }
        - { path: ^/rock, roles: 'IS_AUTHENTICATED_FULLY' }
        - { path: ^/steel, roles: 'IS_AUTHENTICATED_FULLY' }


        
        
        
